import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MockPrep AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
        <Head>
          <link rel="shortcut icon" href="../public/SecondLogo.svg" />
        </Head>
          <Toaster/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
